Document: vulkancapsviewer
Title: Debian vulkancapsviewer Manual
Author: <insert document author here>
Abstract: This manual describes what vulkancapsviewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkancapsviewer/vulkancapsviewer.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkancapsviewer/vulkancapsviewer.ps.gz

Format: text
Files: /usr/share/doc/vulkancapsviewer/vulkancapsviewer.text.gz

Format: HTML
Index: /usr/share/doc/vulkancapsviewer/html/index.html
Files: /usr/share/doc/vulkancapsviewer/html/*.html
